Bormaheco/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts import views
from django.contrib.auth.views import logout
from django.conf import settings
from django.views.generic import TemplateView


urlpatterns = [

    url(r'^admin/', admin.site.urls, name='administration'),

    url(r'^equipment/', include('equipment.urls'), name='equipment'),

    url(r'^rental/', include('rental.urls'), name='rental'),

    url(r'^logout/', logout, {'next_page': settings.LOGIN_REDIRECT_URL}, name='logout'),

    url(r'^logincheckout/', views.login_user_checkout, name='checkout_login'),

    url(r'^register/', views.reqister, name='register'),

    url(r'^login/', views.login_user, name='login'),

    url(r'^checkuser/', views.check_username, name='usercheck'),

    url(r'^$', views.homepage, name='mainpage'),

    url(r'^error/', TemplateView.as_view(template_name='notallowed.html'), name='errorpage'),
]

admin.site.site_header = "Bormaheco Administration"
admin.site.site_title = "Bormaheco Inc. | Admin"

equipment/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf import settings
app_name = 'equipment'
urlpatterns = [
    url(r'^$', views.equipment_index, name='mainpage'),

    url(r'^equipmentdetails(?P<pk>\d+)', views.get_em_equipment, name='getemequipment'),

    url(r'^dispatch/(?P<pk>\d+)', views.dispatch, name='dispatch'),

    url(r'^recall/(?P<pk>\d+)', views.recall, name='recall'),

    url(r'^end_maintenance/', views.end_maintenance, name='end_maintenance'),

    url(r'^start_maintenance/(?P<primary_key>\d+)', views.start_maintenance, name='start_maintenance'),

    url(r'^deleteequipment/(?P<primary_key>\d+)', views.delete_equipment, name='deleteequipment'),

    url(r'^filterequipment/(?P<types>\D\D)/', views.filter_equipment, name='filterequipment'),

    url(r'^addequipment/', views.add_equipment, name='addequipment'),

    url(r'^getequipment/(?P<eqid>\d+)', views.get_equipment, name='getequipment')
]

rental/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from django.conf import settings
from . import views
from django.views.generic import TemplateView
app_name = 'rental'
urlpatterns = [

    url(r'^checkout_cart/', views.checkout_cart, name='checkout_cart'),

    url(r'^transactions/(?P<transaction_type>\D\D)$', views.transactionsfiltered, name='filtered_transactions'),

    url(r'^transactions/(?P<transaction_type>\D\D)/(?P<report>\D\D)/(?P<pk>\d+)', views.transactionitem,
        name='getitem'),

    url(r'^confirmpayment/(?P<pk>\d+)', views.confirmpayment, name='confirmpayment'),

    url(r'^transactions/$', views.transactions, name='transactions'),

    url(r'^confirm_payment_finance/(?P<pk>\d+)', views.confirm_payment_finance, name='financeconfirm'),

    url(r'^checkout/', views.checkout, name='checkout'),

    url(r'^rejectinquiry/(?P<pk>\d+)', views.reject_inquiry, name='rejectinquiry'),

    url(r'^createquotation', views.create_quotation, name='create_quotation'),

    url(r'^deletefromcart/(?P<item_id>\d+)', views.delete_from_cart, name='delete_from_cart'),

    url(r'^addtocart/(?P<item_id>\d+)', views.add_to_cart, name='addtocart'),

    url(r'^reports/$', views.view_rental_reports, name='rentalreports'),
]

equipment/models.py
from django.db import models
from django.utils import timezone
from itertools import chain
from operator import attrgetter

# Create your models here.


class Equipment(models.Model):
    brand = models.CharField(max_length=20)
    name = models.CharField(max_length=50)
    acquisition_cost = models.DecimalField(max_digits=12, decimal_places=2)
    acquisition_date = models.DateField()
    details = models.CharField(max_length=2000)
    TYPE_CODES = (
        ('AC', 'Air Compressor'),
        ('BL', 'Backhoe Loader'),
        ('BR', 'Breaker'),
        ('BD', 'Bulldozer'),
        ('CR', 'Crane'),
        ('DT', 'Dump Truck'),
        ('EX', 'Excavator'),
        ('FT', 'Flatbed Truck'),
        ('FL', 'Forklifts'),
        ('GS', 'Genarating Set'),
        ('LB', 'Low Bed Trailer'),
        ('MT', 'Manlift Truck'),
        ('MC', 'Motorcycle'),
        ('PL', 'Payloader'),
        ('PM', 'Prime Mover'),
        ('RG', 'Road Grader'),
        ('RR', 'Road Roller'),
        ('SL', 'Skidsteer Loader'),
        ('OT', 'Other'),
    )
    type = models.CharField(max_length=2, choices=TYPE_CODES)
    STATUS_CODES = (
        ('IE', 'In Engagement'),
        ('AV', 'Available'),
        ('UM', 'Under Maintenance'))
    status = models.CharField(max_length=2, choices=STATUS_CODES)
    hours_worked = models.IntegerField(default=0)
    total_hours_worked = models.IntegerField(default=0)
    hourly_service_rate = models.DecimalField(max_digits=12, decimal_places=2)
    image = models.ImageField(upload_to="equipmentimages", default='../media/equipmentimages/defaultequipment.png')

    def __str__(self):
        return '{}: {}'.format(self.type, self.name)

    def as_dict(self):
        return {
            'brand': self.brand,
            'name': self.name,
            'acquisitioncost': self.acquisition_cost,
            'acquisitiondate': self.acquisition_date,
            'details': self.details,
            'type': self.get_type_display,
            'status': self.status,
            'hourly_service_rate': self.hourly_service_rate,
            'imageurl': self.image.url,
        }

    def checkconflict(self, index):
        from rental.models import Inquiry
        inquiry2 = Inquiry.objects.get(id=index)
        inquiries = self.inquiryequipment_set.all().exclude(inquiry_id=index)
        if self.status == "UM":
            return True

        if inquiry2.status == "AQ":
            for inquiryequipment in inquiries:
                if inquiryequipment.inquiry.status == "CO":
                    test_start = inquiryequipment.inquiry.start_date
                    test_end = inquiryequipment.inquiry.end_date
                    if test_start <= inquiry2.start_date <= test_end:
                        return True
                    if test_start <= inquiry2.end_date <= test_end:
                        return True

        return False

    def has_engagement(self):
        from rental.models import Inquiry
        inquiries = Inquiry.objects.filter(inquiryequipment__equipment=self).filter(start_date__lte=timezone.now()).\
            filter(end_date__gte=timezone.now()).filter(status="CO")
        if not inquiries:
            return False
        else:
            return True

    def get_previous_transactions(self):
        from rental.models import Inquiry
        inquiries = Inquiry.objects.filter(inquiryequipment__equipment=self).filter(end_date__lt=timezone.now()).\
            filter(status="CO")
        maintenance = MaintenanceTransaction.objects.filter(equipment=self).filter(end_date__lt=timezone.now())
        combined = sorted(chain(inquiries, maintenance), key=attrgetter('end_date'), reverse=True)
        return combined

    def get_roi(self):
        from rental.models import Quotation
        quotation = Quotation.objects.filter(quotationequipment__equipment=self).filter(paid=True).filter(status="PA")
        income = 0
        for x in quotation:
            days = x.inquiry.end_date - x.inquiry.start_date
            days = (days.days + 1) * 24
            income = income + (days * self.hourly_service_rate)

        maintenance = MaintenanceTransaction.objects.filter(equipment=self).filter(end_date__lte=timezone.now())
        maintenance_cost = 0
        for y in maintenance:
            maintenance_cost = maintenance_cost + y.cost

        roi = (income - (maintenance_cost + self.acquisition_cost))/(maintenance_cost + self.acquisition_cost)

        return roi


# WAG TO
#
#    class EquipmentEngagement(models.Model):
#       equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
#        date = models.DateField()
#        start_time = models.TimeField()
#        end_time = models.TimeField()
#
#        def __str__(self):
#            return '{}, {}'.format(self.equipment.name, self.date)


class MaintenanceTransaction(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField(null=True)
    cost = models.DecimalField(max_digits=12, decimal_places=2, null=True)

    def __str__(self):
        return '{}, {}'.format(self.equipment.name, self.start_date)

rental/models.py
from django.db import models
from django.contrib.auth.models import User
from equipment.models import Equipment

# Create your models here.


class Inquiry(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    sent_on = models.DateTimeField()
    STATUS_CODES = (
        ('AQ', 'Awaiting Quotation'),
        ('AR', 'Awaiting Confirmation'),
        ('CO', 'Confirmed'),
        ('RE', 'Rejected'))
    status = models.CharField(max_length=2, choices=STATUS_CODES)
    start_date = models.DateField()
    end_date = models.DateField()
    location = models.CharField(max_length=100)
    comments = models.CharField(max_length=1000, blank=True)

    def __str__(self):
        return '{}:{} - {}'.format(self.get_status_display(), self.customer.username, self.sent_on)

    def related_quotation(self):
        if self.quotation:
            return self.quotation
        else:
            return 'null'

    def getallequipment(self):
        return self.inquiryequipment_set.all()

    def has_conflict(self):
        list_of_equipment = self.inquiryequipment_set.all()
        for list_of_equipment in list_of_equipment:
            result = list_of_equipment.equipment.checkconflict(self.id)
            if result is True:
                return True

        return False


class InquiryEquipment(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    inquiry = models.ForeignKey(Inquiry, on_delete=models.CASCADE)

    def __str__(self):
        return '{}:{} - {}: {}'.format(self.inquiry.get_status_display(), self.inquiry.customer.username,
                                       self.inquiry.sent_on, self.equipment.name)


class Quotation(models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    inquiry = models.OneToOneField(Inquiry, on_delete=models.CASCADE)
    STATUS_CODES = (
        ('PA', 'Accepted'),
        ('RE', 'Rejected'),
        ('AW', 'Awaiting Confirmation'))
    status = models.CharField(max_length=2, choices=STATUS_CODES)
    sent_on = models.DateTimeField()
    paid = models.BooleanField(default=False)
    transportation_cost = models.DecimalField(max_digits=12, decimal_places=2)
    comments = models.CharField(max_length=1000, blank=True)

    def __str__(self):
        return '{}:{} - {}'.format(self.get_status_display(), self.created_by.username, self.sent_on)

    def getprice(self):
        equipment = self.quotationequipment_set
        totalprice = 0
        date = self.inquiry.end_date - self.inquiry.start_date
        date = (date.days + 1) * 24
        for unit in equipment.all():
            totalprice += unit.equipment.hourly_service_rate
        totalprice = totalprice * date
        return totalprice + self.transportation_cost

    def gettotalrental(self):
        equipment = self.quotationequipment_set
        totalprice = 0
        for unit in equipment.all():
            totalprice += unit.equipment.hourly_service_rate
        return totalprice

    def getallequipment(self):
        return self.quotationequipment_set.all()


class QuotationEquipment(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    quotation = models.ForeignKey(Quotation, on_delete=models.CASCADE)

    def __str__(self):
        return '{}:{} - {}: {}'.format(self.quotation.get_status_display(), self.quotation.created_by.username,
                                       self.quotation.sent_on, self.equipment.name)

rental/templates/cart.html
{% load static %}
{% if cart.count == 0 %}
    <h2 class="text-center">Your cart is empty!</h2>
{% else %}
    {% for equipment in cart %}
        <li class="list-group-item">
            <div class="row" style="height: 100px">
                <div class="col-sm-4">
                        <img style="height: 75px; width: 100px;" class="img-responsive"
                             src="{% static equipment.image.url %}">
                </div>
                <div class="col-sm-6">
                    <p style="margin: 15px -20px -15px"><strong>{{ equipment.name }}</strong></p>
                    <p style="margin: 15px -20px -15px"><em>{{ equipment.get_type_display }}</em></p>
                </div>
                <div class="col-sm-1">
                    <a href="{% url 'rental:delete_from_cart' item_id=equipment.id %}">
                        <span style="top: 25px; right: -20px; font-size: 1.5em; color: #3F4643"
                              class="glyphicon glyphicon-trash pull-right"></span>
                    </a>
                </div>
            </div>
        </li>
    {% endfor %}
{% endif %}

rental/templates/finance.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    {% load templatetags %}
    {% csrf_token %}
    <meta charset="UTF-8">
    <title>Bormaheco Inc.</title>
    <!-- Imports JQuery -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Latest compiled and minified JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Global Login -->
    <script type="text/javascript"> var loginurl = {% url 'login' %};</script>
    <script src="{% static 'js/login.js' %}"></script>

    <link rel="icon" href="{% static 'images/icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/finance.css' %}">
</head>
<body>
    <nav class="navbar navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">
                    <img style="height: 250%" src="{% static 'images/bormaheco.png' %}">
                </a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'mainpage' %}" id="navlink">Home</a></li>
                <li><a href="{% url 'equipment:mainpage' %}" id="navlink">Equipment</a></li>
                {% if request.user.is_authenticated %}
                    {% if request.user.useraccount.user_type == "CU" or request.user.useraccount.user_type == "FI" or request.user.useraccount.user_type == "EM" %}
                        <li><a href="{% url 'rental:transactions' %}" id="navlink">Transactions</a></li>
                    {% endif %}
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_superuser == False %}
                    {% if request.user.useraccount.user_type == 'CU' or request.user.useraccount.user_type == Null %}
                    <li>
                        <div class="dropdown">
                            <a id="cart" type="button" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-shopping-cart"></span></a>
                            <ul class="dropdown-menu cart" id="cartDropdown">
                                {% get_cart request %}
                                {% cart_length request as num %}
                                {% if num > 0 %}
                                    <a type="button" style="display:block; margin-top: 10px; margin-bottom: 5px"
                                 href="{% url 'rental:checkout' %}" class="btn btn-warning text-center">Checkout</a>
                                {% endif %}
                            </ul>
                        </div>
                    </li>
                    {% endif %}
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li>
                        <div class="dropdown">
                            <a class="dropdown-toggle" id="userbutton" type="button" data-toggle="dropdown">
                                {{ request.user.username }}
                                <span id="arrow" class="glyphicon glyphicon-triangle-bottom"></span>
                            </a>
                            <ul id="usertools" class="dropdown-menu">
                                {% if request.user.is_superuser %}
                                    <li><a href="{% url 'admin:index' %}">Admin Page</a></li>
                                {% endif %}
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                            </ul>
                        </div></li>
                {% else %}
                    <li>
                        <div class="dropdown" id="logindiv">
                            <a class="dropdown-toggle" id="userbutton" type="button" data-toggle="dropdown">
                                Login
                                <span id="arrow" class="glyphicon glyphicon-triangle-bottom"></span>
                            </a>
                            <ul id="usertools" class="dropdown-menu">
                                <li><label for="login_username_input">Username:</label>
                                <input placeholder="Username" class="form-control" id="login_username_input"
                                       type="text"></li>
                                <li><label for="login_password_input">Password:</label>
                                <input placeholder="Password" class="form-control" id="login_password_input"
                                       type="password"></li>
                                <li><button class="btn btn-default center-block" type="button"
                                            id="login">Login</button></li>
                            </ul>
                        </div></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="row" id="mainpagebody">
        <span class="col-md-1"></span>
        <div class="col-md-10 row">
            <h1>Payment Transactions</h1>
            <table class="table table-bordered table-striped">
                <tr>
					<th>Username</th>
                    <th>Company</th>              
                    <th>Sent On</th>
                    <th>Service Date</th>
                    <th>Status</th>
                </tr>
                {% for x in quotations %}
                    <tr>
                        <td>{{ x.inquiry.customer.username }}</td>
                        <td>{{ x.inquiry.customer.useraccount.company }}</td>
                        <td>{{ x.sent_on }}</td>
                        <td>{{ x.inquiry.start_date }} - {{ x.inquiry.end_date }}</td>
                        <td class="text-center">{{ x.get_status_display }} / <strong>Paid: </strong>{{ x.paid }}
                        {% if x.paid == True and x.status == "AW" %}
                            <br><a style="margin-top: 5px" href="{% url 'rental:financeconfirm' pk=x.id %}"
                                   type="button" class="btn btn-warning">Confirm Payment</a>
                        {% endif %}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</body>
</html>

rental/templates/rentalreport.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    {% load humanize %}
    {% load templatetags %}
    {% csrf_token %}
    <meta charset="UTF-8">
    <title>Bormaheco Inc. | Rental Report</title>
    <!-- Imports JQuery -->
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Latest compiled and minified JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Date Picker -->
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}">
    </script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}">
    </script>
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker3.min.css' %}">

    <!-- Global Login -->
    <script type="text/javascript"> var loginurl = {% url 'login' %};</script>
    <script src="{% static 'js/login.js' %}"></script>

    <link rel="icon" href="{% static 'images/icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/rentalreports.css' %}">
</head>
<body>
    <nav class="navbar navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">
                    <img style="height: 250%" src="{% static 'images/bormaheco.png' %}">
                </a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'mainpage' %}" id="navlink">Home</a></li>
                <li><a href="{% url 'equipment:mainpage' %}" id="navlink">Equipment</a></li>
                {% if request.user.is_authenticated %}
                {% if request.user.user_type == CU or request.user.user_type == FI or request.user.user_type == EM %}
                        <li><a href="{% url 'rental:transactions' %}" id="navlink">Transactions</a></li>
                    {% endif %}
                {% endif %}
                {% if request.user.is_authenticated %}
                    {% if request.user.useraccount.user_type == "EM" %}
                        <li><a href="{% url 'rental:rentalreports' %}" id="navlink">Rental Reports</a></li>
                    {% endif %}
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_superuser == False %}
                    {% if request.user.useraccount.user_type == 'CU' or request.user.useraccount.user_type == Null %}
                    <li>
                        <div class="dropdown">
                            <a id="cart" type="button" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-shopping-cart"></span></a>
                            <ul class="dropdown-menu cart" id="cartDropdown">
                                {% get_cart request %}
                                {% cart_length request as num %}
                                {% if num > 0 %}
                                    <a type="button" style="display:block; margin-top: 10px; margin-bottom: 5px"
                                 href="{% url 'rental:checkout' %}" class="btn btn-warning text-center">Checkout</a>
                                {% endif %}
                            </ul>
                        </div>
                    </li>
                    {% endif %}
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li>
                        <div class="dropdown">
                            <a class="dropdown-toggle" id="userbutton" type="button" data-toggle="dropdown">
                                {{ request.user.username }}
                                <span id="arrow" class="glyphicon glyphicon-triangle-bottom"></span>
                            </a>
                            <ul class="dropdown-menu" id="usertools">
                                {% if request.user.is_superuser %}
                                    <li><a href="{% url 'admin:index' %}">Admin Page</a></li>
                                {% endif %}
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                            </ul>
                        </div></li>
                {% else %}
                    <li>
                        <div class="dropdown" id="logindiv">
                            <a class="dropdown-toggle" id="userbutton" type="button" data-toggle="dropdown">
                                Login
                                <span id="arrow" class="glyphicon glyphicon-triangle-bottom"></span>
                            </a>
                            <ul id="usertools" class="dropdown-menu">
                                <li><label for="login_username_input">Username:</label>
                                <input placeholder="Username" class="form-control" id="login_username_input"
                                       type="text"></li>
                                <li><label for="login_password_input">Password:</label>
                                <input placeholder="Password" class="form-control" id="login_password_input"
                                       type="password"></li>
                                <li><button class="btn btn-default center-block" type="button"
                                            id="login">Login</button></li>
                            </ul>
                        </div></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="row" id="pagebody">
        <span class="col-md-1"></span>
        <div class="col-md-10">
            <form class="form-inline" action="{% url 'rental:rentalreports' %}">
                <div class="form-group" id="date_group">
                            <label for="datestart" class="col-form-label">View Services from: </label>
                            <div class="input-daterange input-group" id="datepicker">
                                <input class="input-sm form-control" id="datestart" name="start"
                                       placeholder="Start Date"/>
                                <span class="input-group-addon">to</span>
                                <input class="input-sm form-control" id="dateend" name="end"
                                        placeholder="End Date"/>
                            </div>
                            <p class="text-danger" id="date_error" hidden></p>
                            <input type="submit" id="submitbutton" class="btn btn-warning">
                </div>
            </form>
            {% if service.count > 0 %}
                <h1 class="text-center">Rental Service Report <br><small> from {{ start_date }} to {{ end_date }}</small></h1>
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Customer</th>
                        <th>Location</th>
                        <th>Date Range</th>
                        <th>Price</th>
                    </tr>
            {% endif %}
            {% for report in service %}
                    <tr>
                        <td>{{ report.inquiry.customer.username }}</td>
                        <td>{{ report.inquiry.location}}</td>
                        <td><strong>Start Date: </strong>{{ report.inquiry.start_date }}<br>
                            <strong>End Date: </strong>{{ report.inquiry.end_date }}</td>
                        <td class="text-right">P{{ report.getprice|intcomma }}</td>
                    </tr>
                {% empty %}
                <h1 class="text-center">No Service Details for those Dates</h1>
            {% endfor %}
            {% if service.count > 0 %}
                    <tr>
                        <td style="border-right: none;"></td>
                        <td style="border-left: none; border-right: none;"></td>
                        <td style="border-left: none; border-right: none;"></td>
                        <td class="text-right" style="border-left: none;"><strong>Total Price: </strong>P{{ total_price|intcomma }}</td>
                    </tr>
                </table>
                <h1 class="text-center">End of Report</h1>
            {% endif %}
        </div>
    </div>
</body>

<script type="text/javascript">
            $('#date_group .input-daterange').datepicker({
                format: "yyyy-mm-dd",
                endDate: "today",
                orientation: "bottom auto",
                autoclose: true
            });
</script>

</html>